# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2895e782e25ba9e5f6d8d52ac399fce9c2efc04c217bbee93f7591bb6075674f2f0a87984cf1f4479afcfac5386bbb1235dad8f9f024b4c427c2e06f759c0818

test:
  secret_key_base: c1ad6597a54efc94636482479910f6002a1b2cd4b6837a33c2982da9b20f58fecb414922de5a66493f4e35524be16c8a43f78e3104ac8567b96da311886b266f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
